//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
            this.Imagen = new HashSet<Imagen>();
        }
    
        public int idProducto { get; set; }
        public int idSubCategoria { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public int stockMinimo { get; set; }
        public int stockActual { get; set; }
        public int stockIdeal { get; set; }
        public string descripcion { get; set; }
        public int descuento { get; set; }
        public int ME_alto { get; set; }
        public int ME_ancho { get; set; }
        public int ME_largo { get; set; }
        public int ME_peso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagen> Imagen { get; set; }
        public virtual SubCategoria SubCategoria { get; set; }
    }
}
